version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: