# Используем официальный образ Python
FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . /app/

# Открываем порт, на котором будет работать сервер
EXPOSE 8000

# Команда для запуска Django-сервера и Celery
CMD ["sh", "-c", "python manage.py migrate && celery -A config worker --loglevel=info & python manage.py runserver 0.0.0.0:8000"]