# Generated by Django 3.2.25 on 2024-10-31 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.TimeField(default=datetime.datetime(2024, 10, 31, 9, 23, 9, 429003, tzinfo=utc), verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly_1', '1 раз в неделю'), ('weekly_2', '2 раза в неделю'), ('weekly_3', '3 раза в неделю'), ('weekly_4', '4 раза в неделю'), ('weekly_5', '5 раз в неделю'), ('weekly_6', '6 раз в неделю')], default='daily', max_length=20, verbose_name='Период')),
                ('reward', models.CharField(max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_to_action', models.DurationField(default=datetime.timedelta(seconds=60), verbose_name='Время на выполнение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('connection_wont', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.wont', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
