# Generated by Django 4.2.16 on 2024-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_wont_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wont",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
